### ISSUE TITLE
Modded versions not working

### ISSUE THREAD

**Issue by Minegar** [CmlLib/CmlLib.Core#15]
I can launch vanilla versions with no problems, but when I tried Optifine/fabric game crashes with this:

_Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW_

Any clue?

**Comment by AlphaBs** [comment]
what exact version did you try to launch?

**Comment by Minegar** [comment]
> what exact version did you try to launch?

This versions worked:
1.16.5
1.16.3
1.13
1.8.9
1.7.10

This versions did not work and they just throw that error:
Optifine 1.16.3
Optifine 1.16.5
fabricloader 1.16.3
LabyMod 1.8.9

I didn't tried any other versions.

**Comment by AlphaBs** [comment]
how did you install those versions?

**Comment by Minegar** [comment]
From their official site, is there a problem with that?

**Comment by AlphaBs** [comment]
There are some problems if you download these versions using TLauncher.
but I haven't launched moded 1.16.x. so i will test these versions and reply you.

**Comment by Minegar** [comment]
> There are some problems if you download these versions using TLauncher.
> but I haven't launched moded 1.16.x. i will test these versions and reply you. 👍

Thanks! TLauncher was the problem. I removed content of .minecraft folder and your launcher is now 100% working with 1.16.5 Optifine and other mods.
